# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(default='YWZ2017', max_length=50),
            preserve_default=False,
        ),
    ]
