# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_instrument_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
