# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_auto_20171104_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='symbol',
            field=models.CharField(default='ZW2017', max_length=60),
            preserve_default=False,
        ),
    ]
