# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20171105_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variation',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variation',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
