# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20171105_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
