# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
