# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transactionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsummary',
            name='absolute_symbol',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
