# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20171113_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=60, null=True),
        ),
    ]
